### ISSUE TITLE
Adicionar suporte ao download de eventos

### ISSUE THREAD

**Issue by alexdemari** [qualitaocupacional/libesocial#2]
O sistema do eSocial tem a funcionalidade de download de eventos via ID ou número de recibo. Esta funcionalidade pode ser utilizada para recuperar informações enviadas ao sistema.

Verificar o Manual do Desenvolvedor versão 1.7

**Comment by andidevel** [comment]
Os métodos foram implementados, na branch *develop*.

Foram validados com sucesso contra os seus respectivos **XSDs**, mas os testes no ambiente de *Produção Restrita* retorna um *internal server error*:

```xml
<detail xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <ExceptionDetail xmlns="http://schemas.datacontract.org/2004/07/System.ServiceModel" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
        <HelpLink i:nil="true"/>
        <InnerException i:nil="true"/>
        <Message>Object reference not set to an instance of an object.</Message>
        <StackTrace>   at ESocial.Dwl.Cirurgico.Wcf.WsSolicitarDownloadEventos.SolicitarDownloadEventosPorNrRecibo(XmlElement solicitacao)
   at SyncInvokeSolicitarDownloadEventosPorNrRecibo(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[] outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
        </StackTrace>
        <Type>System.NullReferenceException</Type>
    </ExceptionDetail>
</detail>
```
Entramos em contato, pelo canal disponível, com o suporte do eSocial.

Mais tarde vamos fazer novos testes para saber se não é uma instabilidade dos servidores do eSocial.

**Comment by andidevel** [comment]
Foi feito o merge do branch *develop* com a *main*. Mas vou deixar a **issue** aberta pois não conseguimos testar os métodos em produção restrita, pois aparentemente qualquer serviço em "https://webservices.producaorestrita.esocial.gov.br/servicos/empregador/dwlcirurgico/*" está retornando o erro **"Object reference not set to an instance of an object""**, como descrito acima.

**Comment by andidevel** [comment]
Confirmado que em **Ambiente de Produção** está funcionando os métodos de download de eventos. Por algum motivo, ainda não divulgado, (visto que entramos em contato com a equipe do **eSocial** através do "Fale Conosco" disponível no site oficial e até o momento não obtivemos respostas), o download de eventos não funciona em **Ambiente de Produção Restrita** (ambiente de testes!!!??!).
