### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by w1lli4w** [qualitaocupacional/libesocial#7]
Mesmo preenchendo todos os campos corretamente do código modelo ele apresenta este erro:
PermissionError: [Errno 13] Permission denied

**To Reproduce**
```
C:\Users\user\eSocialPy\ambiente\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py:61: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch 
to using a 64-bit Python.
  from cryptography.hazmat.bindings.openssl import binding
Traceback (most recent call last):
  File "c:\Users\user\eSocialPy\sender.py", line 31, in <module>
    result = esocial_ws.send(group_id=1)
  File "C:\Users\user\eSocialPy\ambiente\lib\site-packages\esocial\client.py", line 211, in send  
    ws = self.connect(url)
  File "C:\Users\user\eSocialPy\ambiente\lib\site-packages\esocial\client.py", line 95, in connect
    'cafile': self.ca_file
  File "C:\Users\user\eSocialPy\ambiente\lib\site-packages\esocial\client.py", line 47, in __init__
    super(CustomHTTPSAdapter, self).__init__()
  File "C:\Users\user\eSocialPy\ambiente\lib\site-packages\requests\adapters.py", line 156, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "C:\Users\user\eSocialPy\ambiente\lib\site-packages\esocial\client.py", line 54, in init_poolmanager
    context.load_cert_chain(pem.name, password=self.ctx_options.get('key_passwd'))
PermissionError: [Errno 13] Permission denied
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Python version**
Version: 3.7.2

**LIBeSocial version**
Version: 0.0.1rc2

Outra questão é quanto a biblioteca pyOpenSSL, aqui é mencionado que precisa estar na versão inferior a 19, porém quando utiliza a versão anterior à 19 apresenta erro de falta de arquivo.

Só consegui chegar até esse novo erro, utilizando a versão mais atual ( 23).

OBS: Está tudo desbloqueado, pasta, usuário, executando o VSCode no modo ADM, certificado atualizado, tudo correto.

**Comment by andidevel** [comment]
Bom, pelo erro, isso parece um problema com arquivos temporários no windows.

Para testar, tente fazer as seguintes modificações:

### Arquivo `utils.py`

Altere o código:
```python
@contextlib.contextmanager
def encrypt_pem_file(cert_data, cert_pass):
    crypto_key = cert_data['key'].to_cryptography_key()
    pem_pvkey_bytes = crypto_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.BestAvailableEncryption(cert_pass.encode('utf-8'))
    )
    fp = tempfile.NamedTemporaryFile('w')
    fp.write(cert_data['cert_str'].decode('utf-8'))
    fp.write(pem_pvkey_bytes.decode('utf-8'))
    fp.flush()
    try:
        yield fp
    finally:
        fp.close()
```
para:
```python

def encrypt_pem_file(cert_data, cert_pass):
    crypto_key = cert_data['key'].to_cryptography_key()
    pem_pvkey_bytes = crypto_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.BestAvailableEncryption(cert_pass.encode('utf-8'))
    )
    fp = tempfile.NamedTemporaryFile('w', delete=False)
    temp_filename = fp.name
    fp.write(cert_data['cert_str'].decode('utf-8'))
    fp.write(pem_pvkey_bytes.decode('utf-8'))
    fp.flush()
    fp.close()
   return temp_filename
```
### Arquivo `client.py`

Altere o código:
```python
class CustomHTTPSAdapter(HTTPAdapter):

    def __init__(self, ctx_options=None):
        self.ctx_options = ctx_options
        super(CustomHTTPSAdapter, self).__init__()

    def init_poolmanager(self, *args, **kwargs):
        context = create_urllib3_context()
        if self.ctx_options is not None:
            context.load_verify_locations(self.ctx_options.get('cafile'))
            with encrypt_pem_file(self.ctx_options.get('cert_data'), self.ctx_options.get('key_passwd')) as pem:
                context.load_cert_chain(pem.name, password=self.ctx_options.get('key_passwd'))
        kwargs['ssl_context'] = context
        return super(CustomHTTPSAdapter, self).init_poolmanager(*args, **kwargs)

    def proxy_manager_for(self, *args, **kwargs):
        context = create_urllib3_context()
        if self.ctx_options is not None:
            context.load_verify_locations(cafile=self.ctx_options.get('cafile'))
            with encrypt_pem_file(self.ctx_options.get('cert_data'), self.ctx_options.get('key_passwd')) as pem:
                context.load_cert_chain(pem.name, password=self.ctx_options.get('key_passwd'))
        kwargs['ssl_context'] = context
        return super(CustomHTTPSAdapter, self).proxy_manager_for(*args, **kwargs)
```
para:
```python
class CustomHTTPSAdapter(HTTPAdapter):

    def __init__(self, ctx_options=None):
        self.ctx_options = ctx_options
        super(CustomHTTPSAdapter, self).__init__()

    def init_poolmanager(self, *args, **kwargs):
        context = create_urllib3_context()
        if self.ctx_options is not None:
            context.load_verify_locations(self.ctx_options.get('cafile'))
            pem_filename = encrypt_pem_file(self.ctx_options.get('cert_data'), self.ctx_options.get('key_passwd'))
            context.load_cert_chain(pem_filename, password=self.ctx_options.get('key_passwd'))
            os.unlink(pem_filename)
        kwargs['ssl_context'] = context
        return super(CustomHTTPSAdapter, self).init_poolmanager(*args, **kwargs)

    def proxy_manager_for(self, *args, **kwargs):
        context = create_urllib3_context()
        if self.ctx_options is not None:
            context.load_verify_locations(cafile=self.ctx_options.get('cafile'))
            pem_filename = encrypt_pem_file(self.ctx_options.get('cert_data'), self.ctx_options.get('key_passwd'))
            context.load_cert_chain(pem_filename, password=self.ctx_options.get('key_passwd'))
            os.unlink(pem_filename)
        kwargs['ssl_context'] = context
        return super(CustomHTTPSAdapter, self).proxy_manager_for(*args, **kwargs)
```

Não tenho um ambiente windows para testar, então não sei se esse código vai funcionar. Por favor faça o teste no seu ambiente e depois nos diga se deu certo.

>> Outra questão é quanto a biblioteca pyOpenSSL, aqui é mencionado que precisa estar na versão inferior a 19, porém quando >> utiliza a versão anterior à 19 apresenta erro de falta de arquivo.

Estamos atualizando a lib para funcionar com as versões mais novas da pyOpenSSL. Na branch [develop](https://github.com/qualitaocupacional/libesocial/tree/develop), que tem a versão mais nova em desenvolvimento, estamos usando a versão *22.1.0* da pyOpenSSL. Estamos fazendo ajustes para suportar a versão mais nova, bem como dropar o suporte ao Python 2.X e utilizar as versões mais novas dos layouts do **eSocial**.

**Comment by w1lli4w** [comment]
Obrigado pela resposta!

Infelizmente não funcionou.

agora apresenta este erro:

  File "C:\Users\user\eSocialPy\venv\Lib\site-packages\esocial\client.py",
line 54, in init_poolmanager
    context.load_cert_chain(pem_filename,
password=self.ctx_options.get('key_passwd'))
TypeError: certfile should be a valid filesystem path

Em sex., 27 de jan. de 2023 às 21:49, Anderson R. Livramento <
***@***.***> escreveu:

**Comment by andidevel** [comment]
> TypeError: certfile should be a valid filesystem path

Hummm... vamos debugar. Altere o código em questão (no arquivo `client.py`) com seguinte código (só vou mostrar o código relevante, que deve ser entre as linhas 53 e 54):
```python
pem_filename = encrypt_pem_file(self.ctx_options.get('cert_data'), self.ctx_options.get('key_passwd'))
# adicione aqui o seguinte:
import pdb; pdb.set_trace()
context.load_cert_chain(pem_filename, password=self.ctx_options.get('key_passwd'))
```

E rode novamente o seu teste (em linha de comando). A execução deve parar mostrando o prompt do PDB no console, o que deve ser algo parecido com isso:
```
->  pem_filename = encrypt_pem_file(self.ctx_options.get('cert_data'), self.ctx_options.get('key_passwd'))
            context.load_cert_chain(pem_filename, password=self.ctx_options.get('key_passwd'))
(Pdb) _
```
Digite os seguintes "comandos" e depois **ENTER**:
```
(Pdb) pem_filename
<deve aparecer o conteúdo da variável "pem_filename">

(Pdb) type(pem_filename)
<deve aparecer o tipo da variável "pem_filename">

(Pdb) c
<deve continuar a execução normalmente e levantar a exceção...>
```
Copie os resultados do conteúdo e tipo da variável **pem_filename** e coloque-os aqui nessa thread.

**Comment by w1lli4w** [comment]
Bom dia!

Valeu pela atenção.

Vamos aos retornos:

(Pdb) pem_filename
<contextlib._GeneratorContextManager object at 0x0000019F57732690>
(Pdb) type(pem_filename)
<class 'contextlib._GeneratorContextManager'>

E o erro permanece o mesmo:
File "C:\Users\user\eSocialPy\venv\Lib\site-packages\esocial\client.py",
line 58, in init_poolmanager
    context.load_cert_chain(pem_filename,
password=self.ctx_options.get('key_passwd'))
TypeError: certfile should be a valid filesystem path

Em ter., 31 de jan. de 2023 às 08:54, Anderson R. Livramento <
***@***.***> escreveu:

**Comment by andidevel** [comment]
> (Pdb) pem_filename
 <contextlib._GeneratorContextManager object at 0x0000019F57732690>

Acho que você não apagou o `@contextlib.contextmanager` antes da função `encrypt_pem_file(cert_data, cert_pass)` no arquivo `utils.py`.

**Comment by w1lli4w** [comment]
Valeu irmão, era isso mesmo! Agora deu certo aqui!!

Muito obrigado!

Em ter., 31 de jan. de 2023 às 10:01, Anderson R. Livramento <
***@***.***> escreveu:

**Comment by andidevel** [comment]
Mas é bom saber que essa abordagem não funciona no windows. Vamos ter que alterar isso se quisermos que a lib funcione em outras plataformas.

Obrigado pelos testes.

**Comment by w1lli4w** [comment]
valeu, TMJ

Em ter., 31 de jan. de 2023 às 15:15, Anderson R. Livramento <
***@***.***> escreveu:

**Comment by andidevel** [comment]
Resolvido na branch [develop](https://github.com/qualitaocupacional/libesocial/tree/develop), commit [6ad4853](https://github.com/qualitaocupacional/libesocial/commit/6ad4853d903866f381182e7e9aee6b2fe8781dd1).
